### ISSUE TITLE
[Feature Request] Denoised Microphone as selectable Input device

### ISSUE THREAD

**Issue by C-512L** [josh-richardson/cadmus#11]
it have sense that you could just select the Denoised Microphone as an input device in apps like Discord, Skype, etc directly from their settings rather than having to do it manually from pulseaudio settings

**Comment by josh-richardson** [comment]
I believe this limitation is due to applications like discord excluding virtual outputs from their list of available devices. I'm not sure that this is a problem that Cadmus can solve - however, I'll leave this issue open to see if anyone in the community has ideas.

**Comment by C-512L** [comment]
at least for me, in pavucontrol it shows "Denoised Microphone" as a monitor instead of a virtual device input
![image](https://user-images.githubusercontent.com/29307937/86064817-58f76a80-ba6e-11ea-9964-4a4cd03ad124.png)
![image](https://user-images.githubusercontent.com/29307937/86064867-69a7e080-ba6e-11ea-853f-393d50b5a8d0.png)

**Comment by josh-richardson** [comment]
You're right there. As far as I can see in my own testing, Discord only shows physical input devices. However I'll look into the possibility of getting it to show others.

![image](https://user-images.githubusercontent.com/13924368/86065414-7543d900-ba67-11ea-8144-c6f06226dd32.png)

**Comment by LoreRealm** [comment]
So as far as we know... You cannot use this with discord?

**Comment by thebitstick** [comment]
@yurgburg You can, you just have to manually set Discord to "record" from the Denoised Microphone. Then it will properly capture.

**Comment by LoreRealm** [comment]
@thebitstick how would I do that? It doesn't show denoised microphone

**Comment by thebitstick** [comment]
At least when testing with Discord's mic check feature, this is what I did.
I first went to the Recording tab in pavucontrol:
![image](https://user-images.githubusercontent.com/13919134/86078223-3efc5e80-ba53-11ea-92cf-b421ace27b9b.png)
And then I switched the monitor:
![image](https://user-images.githubusercontent.com/13919134/86078291-65ba9500-ba53-11ea-8aec-4e15170717e9.png)

**Comment by LoreRealm** [comment]
I think I got it working thanks bitstick

**Comment by nicolas-abril** [comment]
You can create a virtual input device using 

    [pacmd] load-module module-remap-source master=mic_denoised_out.monitor source_name=mic_remap source_properties="device.description='DenoisedRemap'"

This redirects `mic_denoised_out.monitor` to a Virtual Input Device called mic_remap.
Discord can't detect Cadmus because it's only a monitor and not a "proper" input device.

**Comment by josh-richardson** [comment]
> You can create a virtual input device using
> 
> ```
> [pacmd] load-module module-remap-source master=mic_denoised_out.monitor source_name=mic_remap source_properties="device.description='DenoisedRemap'"
> ```
> 
> This redirects `mic_denoised_out.monitor` to a Virtual Input Device called mic_remap.
> Discord can't detect Cadmus because it's only a monitor and not a "proper" input device.

I'll certainly look into doing this.

**Comment by josh-richardson** [comment]
This has been addressed in #26 & can be enabled in Cadmus 0.0.2 and as such I'm closing this issue. Please do re-open it if the new version doesn't fully solve this issue.
