### ISSUE TITLE
Add better descriptions for the sinks

### ISSUE THREAD

**Issue by nicolas-abril** [josh-richardson/cadmus#16]
Currently, Cadmus creates two devices with Pulseaudio.

`mic_denoise_out` has no description, giving it the default of `Null Output`.  
`mic_raw_in` gets the description of `LADSPA Plugin Noise Suppresor for Voice (Mono) on Null Output` from librnnoise_ldspa.
`mic_denoise_out.monitor` has a better description, `Denoised Microphone`.

These names are horrible, confusing and cluttering. I propose `Cadmus Denoised Microphone Output` for the null sink, `Cadmus Raw Microphone Redirect` for the raw loopback, not giving a description to the monitor and creating a Virtual Input Device, as I mentioned in #11 , which would get the description of `Cadmus Denoised Microphone`.

Edit: The precise names are not that important, as long as they give an idea to whom they belong (Cadmus) and what they are used.

**Comment by josh-richardson** [comment]
This has been addressed in #26 and as such I'm closing this issue. Please do re-open it if the new version doesn't fully solve this issue.
