### ISSUE TITLE
The deb file reports the license as proprietary

### ISSUE THREAD

**Issue by mark-goodall** [josh-richardson/cadmus#18]
The deb file and the repository have different license details

**Comment by josh-richardson** [comment]
Firstly, as far as I can see, the license is reported as Unknown on the deb file:
```
dpkg --info cadmus.deb 
 new Debian package, version 2.0.
 size 35601032 bytes: control archive=3978 bytes.
     251 bytes,    11 lines      control              
    9166 bytes,   123 lines      md5sums              
 Package: cadmus
 Version: 1.0
 License: unknown
 Vendor: Joshua Richardson
 Architecture: amd64
 Maintainer: <@2148c3ef37b4>
 Installed-Size: 90744
 Section: default
 Priority: extra
 Homepage: http://example.com/no-uri-given
 Description: no description given
```


If we look at how fbs handles the creation of the .deb file [here](https://github.com/mherrmann/fbs/blob/master/fbs/installer/linux.py), we can see that it doesn't easily allow the user to specify the license name. I may at some point open a PR in fbs to allow the license in the deb file to be specified, but for now, given that it's not directly specifying the license as at odds with the actual project license, I don't think this is a priority. Thanks for reporting though.

**Comment by josh-richardson** [comment]
Opened [this PR](https://github.com/mherrmann/fbs/pull/204) in fbs to enable functionality to allow this.

**Comment by mark-goodall** [comment]
Ah, I'm sorry I didn't look in enough detail, gnome-software (gui based dpkg installer) reports deb with unknown licenses as proprietary
