### ISSUE TITLE
High latency

### ISSUE THREAD

**Issue by EmeraldSnorlax** [josh-richardson/cadmus#19]
Not sure if this issue belongs here, or upstream to Werman's plugin, but there is very high latency between speaking and hearing output being looped back to me (3-5 seconds +)

My pulseaudio version is 13.0, I am using Arch Linux, and am using a generic analog microphone
Are there any possible solutions to this? Without noise suppression latency isn't an issue (sub 0.5s latency by ear)

**Comment by josh-richardson** [comment]
It is likely an upstream issue. This may be due to the relatively high compute demands of rnnoise - it often uses 5-10% of my one of my CPU threads on a Ryzen 3900X - however, five seconds does sound rather excessive.

**Comment by werman** [comment]
rnnoise itself is quite low latency, the latency is one frame of sound data. The main source of latency is pulseaudio. But yeah `3-5` is a configuration issue, I'd expect 100-200ms from pulseaudio.

>  it often uses 5-10% of my one of my CPU threads on a Ryzen 3900X

Also most likely the core isn't fully clocked, in such case.

**Comment by josh-richardson** [comment]
Given @werman's response & the lack of anyone else reporting this issue, I'd say it's likely to do with the setup on your local machine. I'm going to close this one, but do feel free to re-open it if you have reason to believe it's an issue with Cadmus.

**Comment by werman** [comment]
Also one could try advice from https://github.com/werman/noise-suppression-for-voice/issues/18

**Comment by bakana808** [comment]
I was having the same issue as well (~2-3 second delay) and fixed the issue by changing my microphone from an Analog Stereo Input to a Digital Stereo Input with `pavucontrol` .
