### ISSUE TITLE
Bugfix + Suggestion

### ISSUE THREAD

**Issue by ghost** [josh-richardson/cadmus#21]
Hi. Firstly, This program is great. And abstracts multiple features that would normally require opening up pavucontrol into a nice neat little applet. And I do like that. But it's shortcoming is it does not work on discord, And it does not work on chrome/chromium. And being as many audio/video call programs rely on chromium (which is sad seeing that google follows the footsteps of microsoft with their **embrace, extend, extinguish**) 

Secondly, If it's any help atall v4l2loopback does not work on discord if you load it with no paramaters. But if you load it with
**sudo modprobe v4l2loopback exclusive_caps=1** Discord picks up whatever you're outputting just fine and accepts it. May or not be helpful in some way. 

This is a very neat program and I would like to see it have some success as each program having their own form of noise supression is archaic dogshit and something that should realistically be handeled by the microphone driver in the first place for the sake of consistency, optimization, space saving, etc. But this is one step closer to that.

**Comment by josh-richardson** [comment]
This has been addressed in #26 and as such I'm closing this issue. Please do re-open it if the new version doesn't fully solve this issue.
