### ISSUE TITLE
.deb file appears as "proprietary" in Ubuntu 20.04

### ISSUE THREAD

**Issue by JurgenG** [josh-richardson/cadmus#30]
Heya,
when installing cadmus on Ubuntu 20.04, it gets licensed as "Proprietary", while the license file in GitHub, clearly puts it as GPL 3.0. Inspecting the .deb file, learns that it contains no license information.

```
dpkg --info cadmus.deb 
 new Debian package, version 2.0.
 size 35615736 bytes: control archive=4095 bytes.
     345 bytes,    11 lines      control              
    9293 bytes,   125 lines      md5sums              
 Package: cadmus
 Version: 1.0
 License: unknown
 Vendor: Joshua Richardson
 Architecture: amd64
 Maintainer: Joshua Richardson <joshua@richardson.tech>
 Installed-Size: 90765
 Section: default
 Priority: extra
 Homepage: https://github.com/josh-richardson/cadmus/
 Description: A GUI frontend for @werman's Pulse Audio real-time noise suppression plugin 
```

Slide 33 here can be of aid: https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf

**Comment by josh-richardson** [comment]
Please check other issues before reporting: https://github.com/josh-richardson/cadmus/issues/18
