### ISSUE TITLE
What is the working principle Cadmus?

### ISSUE THREAD

**Issue by Doroshenko-T** [josh-richardson/cadmus#35]
Hello, friend!

It's just a question. The application "RTX Voice" uses "neural networks" and "artificial intelligence" for its work.
Does your application "Cadmus" use them too? What is the principle of its work?

**Comment by vchernin** [comment]
While RTX voice is meant to be entirely an Nvidia project, Cadmus, NoiseTorch, and other noise suppression apps for linux usually use the [Xiph.org/Mozilla RNNoise base library](https://jmvalin.ca/demo/rnnoise/) along with [a plugin for PulseAudio](https://github.com/werman/noise-suppression-for-voice). The base library is where the actual noise suppression would take place.

Per the RNNoise site:

> This demo presents the RNNoise project, showing how deep learning can be applied to noise suppression. The main idea is to combine classic signal processing with deep learning to create a real-time noise suppression algorithm that's small and fast. No expensive GPUs required — it runs easily on a Raspberry Pi. The result is much simpler (easier to tune) and sounds better than traditional noise suppression systems (been there!). 

There is more technical info surrounding [integrating noise cancellation into PulseAudio here](https://fedoramagazine.org/real-time-noise-suppression-for-video-conferencing/).

**Comment by Doroshenko-T** [comment]
Ok, thank you. Well, I have successfully installed Cadmus v 1.0 on Debian 9/64.
He It starts, but unfortunately does not work at all, because he not configurable in PulseAudio :-(

**Comment by Doroshenko-T** [comment]
Friend, how do I tune Cadmus on Debian 9? 
I installed it, but he doesn't want to work.

**Comment by mainmachine** [comment]
Cadmus is pretty simple - as far as UI it's limited to an applet/indicator in your panel. When you run it, that only starts the indicator. To enable the noise cancellation you right click on the indicator, hover over "Enable Noise Suppression", then select your microphone device. Disable in a similar manner by interacting with the indicator.

**Comment by Doroshenko-T** [comment]
Dear, this is easy to understand and easy to do, no prompts are required.
I did it, but Cadmus doesn't work.
The problem is quite different: what settings are needed in the PulseAudio Volume Control?

![PulseAudio Volume Control](https://user-images.githubusercontent.com/61428202/90269632-974fba00-de61-11ea-97d8-27942df53142.png)

**Comment by joeykrim** [comment]
> Dear, this is easy to understand and easy to do, no prompts are required.
> I did it, but Cadmus doesn't work.
> The problem is quite different: what settings are needed in the PulseAudio Volume Control?
> 
> ![PulseAudio Volume Control](https://user-images.githubusercontent.com/61428202/90269632-974fba00-de61-11ea-97d8-27942df53142.png)

Options appear under output and input as it's filtering the input of your microphone/input to remove background noise
![image](https://user-images.githubusercontent.com/208641/90357850-2814ca00-e009-11ea-8a23-3c187fe4208b.png)
![image](https://user-images.githubusercontent.com/208641/90357857-2d721480-e009-11ea-9ab2-a15311642b58.png)
