### ISSUE TITLE
Can you use this in the terminal

### ISSUE THREAD

**Issue by Goddard** [josh-richardson/cadmus#39]
I have a little baby monitor and I wanted to try and cancel out a sound machine that basically makes wave sounds as a kind of white noise to prevent the babies from waking up because of racket going on in the house.  

The device I am running it on is a raspberry pi 4 and I have a mic attached to it.  The raspberry pi doesn't currently run with a graphical interface.  I might be able to start one up, but I was curious if I even had to and what my luck would be if I tried using this software.

Thanks

**Comment by nicolas-abril** [comment]
You can use the noise suppressing plugin directly (https://github.com/werman/noise-suppression-for-voice), if you check Cadmus' main.py it shows how to use the plugin

**Comment by josh-richardson** [comment]
As mentioned by the previous comment, I think Werman's noise-suppression repo is the right way to go if you want noise suppression without using a GUI.
