### ISSUE TITLE
Is cadmus development dead?

### ISSUE THREAD

**Issue by culebrasolida** [josh-richardson/cadmus#42]
Is cadmus dead? Noisetorch is still pretty active as far as I know but their noise suppression algorithm seems to aggressive for me, more like a Noise Gate. Cadmus runs so much better, but I'd love to see more activity, IT IS very promising.

**Comment by PhilipMottershead** [comment]
He did a commit on a pull request 2 weeks ago probably not

**Comment by josh-richardson** [comment]
No, pull requests are very welcome, for bug fixes as well as new features. However, I do have limited time at the moment to write new code.
