### ISSUE TITLE
Icon not visible on ZorinOS 15.3

### ISSUE THREAD

**Issue by CodeThomnics** [josh-richardson/cadmus#44]
Hi,

I've installed the extension but the icon is not visible. Not even with the TopIcons extension installed.

**Comment by livkx** [comment]
What desktop environment is that? I hate doing this but it looks as though the author is no longer maintaining the repo, so I’ve started working on keeping it maintained on my fork at livkx/cadmus, if you could please try using the latest .deb release from there and create an issue there if you have problems still, and I’ll try my best to fix it.
