### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by truecryingdev** [josh-richardson/cadmus#52]
Hi there @josh-richardson 

I would like to make the AUR package. Can I work on this?

**Comment by josh-richardson** [comment]
If you'd like to maintain an AUR package, that's fine by me. As it is, I unfortunately have quite limited time to maintain this project.

**Comment by truecryingdev** [comment]
Yeah, I have no problem maintaining the AUR package. Thank you!

**Comment by tingvarsson** [comment]
There's already AUR packages available;
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=noisetorch&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by truecryingdev** [comment]
> There's already AUR packages available;
> https://aur.archlinux.org/packages/?O=0&SeB=nd&K=noisetorch&outdated=&SB=n&SO=a&PP=50&do_Search=Go

But that is not the same software. Or am I missing something here?

**Comment by tingvarsson** [comment]
haha it's not. i had to many tabs opened.. for some reason I thought I read issues for noisetorch and not cadmus. #my-bad
