### ISSUE TITLE
Additional option to denoise audio output

### ISSUE THREAD

**Issue by jakubiakdev** [josh-richardson/cadmus#58]
It would be nice to denoise audio output, for example if you're speaking to someone who has noise in the background and they can't install the denoiser. 
This also would make it more familiar to RTX Voice.
I think good implementation would be for additional checkbox like "Allow denosing the output" so the audio devices wouldn't be confused

**Comment by cornzy** [comment]
I think this is a duplicate of #33

**Comment by jakubiakdev** [comment]
Oh shoot, this is a duplicate! Sorry
