### ISSUE TITLE
No audio on Arch Linux

### ISSUE THREAD

**Issue by cyruzin** [josh-richardson/cadmus#69]
I'm using Arch Linux with Gnome 40.1 (Wayland). I installed this package through AUR, it creates the source, I select it in my browser, I record it, but the audio plays without sound.

**Comment by m5r** [comment]
I'm using Manjaro with kernel 5.11 and it's been working fine. Which kernel version are you using?

**Comment by cyruzin** [comment]
> I'm using Manjaro with kernel 5.11 and it's been working fine. Which kernel version are you using?

5.10 LTS. I managed to get it to work from the command line, but not from Cadmus.

**Comment by m5r** [comment]
I'm not sure what's the difference. My steps look like this: start cadmus, enable noise suppression on my mic, pick this new audio input cadmus created in whatever tool I use

**Comment by cyruzin** [comment]
I am closing this issue. If someone needs help with Arch Linux, feel free to reopen it.
