### ISSUE TITLE
No status bar applet

### ISSUE THREAD

**Issue by Kastakin** [josh-richardson/cadmus#7]
I'm on Arch with GNOME as DE, I've tried running Cadmus from the appimage and from the extracted .zip but in neither case I get the applet in the status bar.
The Cadmus process it's running but I get no effect (testing on Discord, using default input)
Are there any dependencies not explicitly stated as required? 
I can give more info if needed, I don't know what could be useful for troubleshooting here

**Comment by josh-richardson** [comment]
There are no dependencies other than PulseAudio (installed on most distros OOTB). Are you using Wayland by any chance? Cadmus uses PyQt5, which I've heard doesn't play nicely out of the box with Wayland. Otherwise, I'm unsure & will have to dig deeper.

**Comment by Kastakin** [comment]
I'm on Xorg unfortunately. I'm also running PulseAudio (came OOTB as you said. 
System is up to date (last system upgrade 1hr ago).

At your disposal for any log files/test you might need to pinpoint the problem! :)

**Comment by josh-richardson** [comment]
The initial version basically has no logging to speak of - I wanted to get something basic out there and gauge response before making it into something more production ready. I'll be releasing 0.0.2 in a day or two, which should include better logging - which hopefully will let us get to the bottom of this.

**Comment by Kastakin** [comment]
I'm not an expert by any mean but I know my way around python, I will try to give a look to the project in the meantime!

**Comment by thebitstick** [comment]
Tray Icon works for me with the [TopIcons Plus Git](https://extensions.gnome.org/extension/2311/topicons-plus/) extension on GNOME/Wayland.

**Comment by Kastakin** [comment]
> Tray Icon works for me with the [TopIcons Plus Git](https://extensions.gnome.org/extension/2311/topicons-plus/) extension on GNOME/Wayland.

This did the trick! The Apptry icon is there now
Apparently the Apptray icon created by PyQt5 isn't liked thaat much by GNOME.
